### ISSUE TITLE
something went poop

### ISSUE THREAD

**Issue by themattdobson** [mamuso/sketch-designdoc#2]
![screen shot 2016-11-10 at 1 17 28 pm](https://cloud.githubusercontent.com/assets/23386417/20188919/ef21685e-a748-11e6-85a8-c034ba46cb12.png)

Just installed the extension and I am getting this error when trying to run it. Thanks for your help.

**Comment by mamuso** [comment]
Hi, @themattdobson, 
I just pushed a fix and now it should be working properly. Download it again and let me know if now works for you.

**Comment by themattdobson** [comment]
Thanks Man. It works!

What a great extension!

**Comment by mamuso** [comment]
Thanks man, I'm glad you like it.
