### ISSUE TITLE
Text in symbols export very small

### ISSUE THREAD

**Issue by jonasdenil** [mamuso/sketch-designdoc#5]
When exporting artboards which contain symbols, the text in those symbols are exported too small. Pretty enoying bug, although very usefull plugin! 

Original design:
![screen shot 2016-11-24 at 10 52 58](https://cloud.githubusercontent.com/assets/10938544/20594021/dff19e8e-b234-11e6-98e9-4127781badf9.png)

Exported artboard:
![screen shot 2016-11-24 at 10 52 34](https://cloud.githubusercontent.com/assets/10938544/20594041/f49a4098-b234-11e6-9314-727015242031.png)

**Comment by alexeiboronnikov** [comment]
Same here

**Comment by mamuso** [comment]
I think I know where the problem is. To get a retina-friendly export, the plugin scales the content x2, and the text layers inside symbols don't seem to respond to the scale action.

I'm looking for possible solutions, will keep you posted.

**Comment by mamuso** [comment]
It should work right now :D

**Comment by jonasdenil** [comment]
Woah, thanks a lot man! Really helped our team out ;)

**Comment by mamuso** [comment]
@jonasdenil glad to hear!
