### ISSUE TITLE
Something went 

### ISSUE THREAD

**Issue by leebongs** [mamuso/sketch-designdoc#8]
I've got this alert message
How can I have some workaround? 

{
    column = 74;
    line = 155;
    sourceURL = "/Users/UserMacName/Library/Application Support/com.bohemiancoding.sketch3/Plugins/DesignDoc.sketchplugin/Contents/Sketch/export.cocoascript";
}

**Comment by mamuso** [comment]
Hi! I'd need a bit of information to help you:

- Which version of Sketch are you using?
- Which version of the plugin are you using?
- How did you install the plugin?

Thanks!

**Comment by themattdobson** [comment]
Everything is working hunky dory now. We're loving the plugin.
